package com.example.mediaplayerapp.utils

const val MEDIA_CHANNEL_ID = "MEDIA_NOTIFICATION_CHANNEL_ID"
const val MEDIA_CHANNEL_NAME = "MEDIA_NOTIFICATION_CHANNEL"
const val MEDIA_CHANNEL_DESCRIPTION = "NOTIFICATION CHANNEL FOR MEDIA"

const val ALARM_CHANNEL_ID = "ALARM_NOTIFICATION_CHANNEL_ID"
const val ALARM_CHANNEL_NAME = "ALARM_NOTIFICATION_CHANNEL"
const val ALARM_CHANNEL_DESCRIPTION = "NOTIFICATION CHANNEL FOR ALARM"

const val PLAY = "PLAY"
const val PAUSE = "PAUSE"
const val NEXT = "NEXT"
const val PREV = "PREV"